---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - smartmontools
      - rsync
    state: present
    update_cache: true

- name: Install drive-func.sh
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/scripts/drive-func.sh"
    dest: /usr/local/sbin/drive-func.sh
    owner: root
    group: root
    mode: '0755'

- name: Install record-drive-stats.sh
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/scripts/record-drive-stats.sh"
    dest: /usr/local/sbin/record-drive-stats.sh
    owner: root
    group: root
    mode: '0755'

- name: Create SMART report directory
  ansible.builtin.file:
    path: /var/local/drive-stats
    state: directory
    owner: hbarta
    group: hbarta
    mode: '0755'

- name: Install SMART recorder service
  ansible.builtin.template:
    src: smart-drive-stats-recorder.service.j2
    dest: /etc/systemd/system/smart-drive-stats-recorder.service
    owner: root
    group: root
    mode: '0644'

- name: Install SMART recorder timer
  ansible.builtin.template:
    src: smart-drive-stats-recorder.timer.j2
    dest: /etc/systemd/system/smart-drive-stats-recorder.timer
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start SMART recorder timer
  ansible.builtin.systemd:
    name: smart-drive-stats-recorder.timer
    enabled: true
    state: started