---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - rsync
    state: present
    update_cache: true

- name: Install collect-drive-stats.sh
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/scripts/collect-drive-stats.sh"
    dest: /usr/local/sbin/collect-drive-stats.sh
    owner: root
    group: root
    mode: '0755'

- name: Create SMART report directory
  ansible.builtin.file:
    path: /var/local/drive-stats
    state: directory
    owner: hbarta
    group: hbarta
    mode: '0755'

- name: Create drive-stats configuration directory
  ansible.builtin.file:
    path: /etc/drive-stats
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate SMART report host list
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/drive-stats/hosts
    owner: root
    group: root
    mode: '0644'

- name: Install SMART collector service
  ansible.builtin.template:
    src: smart-drive-stats-collector.service.j2
    dest: /etc/systemd/system/smart-drive-stats-collector.service
    owner: root
    group: root
    mode: '0644'

- name: Install SMART collector timer
  ansible.builtin.template:
    src: smart-drive-stats-collector.timer.j2
    dest: /etc/systemd/system/smart-drive-stats-collector.timer
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start SMART collector timer
  ansible.builtin.systemd:
    name: smart-drive-stats-collector.timer
    enabled: true
    state: started